---
# file: roles/django/tasks/main.yml

- name: Install django
  pip: name=django virtualenv={{ venv_dir }}

- name: Install lxml requirements
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  sudo: True
  with_items:
    - libxml2-dev
    - libxslt-dev
    - libz-dev 
    - python-dev
    - libffi-dev
    - libssl-dev

- name: install required python packages
  pip: name={{ item }} virtualenv={{ venv_dir }}
  with_items:
    - python-dateutil
    - requests
    - lxml
    - cssselect
    - requests[security]

- file: path="{{ database_dir }}" owner="{{ ansible_ssh_user }}" group=root mode=0774 state=directory
  sudo: True

- file: path="{{ static_dir }}" owner="{{ ansible_ssh_user }}" group=www-data mode=0774 state=directory
  sudo: True

- name: sync the database, apply migrations, collect static content
  django_manage:
    command: "{{ item }}"
    app_path: "{{ source_dir }}"
    virtualenv: "{{ venv_dir }}"
  with_items:
    # - syncdb
    # - migrate
    - collectstatic

- name: Copy database
  copy: src="../../database/db.sqlite3" dest={{ database_dir }}/db.sqlite3 

- name: Create scraping service
  template: src=templates/scraping.conf dest=/etc/init/scraping.conf
  sudo: True
  notify: restart scraping

